version: "3.9"
networks:
    herbario:
      driver: bridge
    tasks:
      driver: bridge
    database:
      driver: bridge
volumes:
  postgres:
    external: false
  postgres_config:
    external: false

services:
  db:
    image: postgres:14.2-alpine
    container_name: herbariumdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=herbarium
    volumes:
      - postgres:/var/lib/postgres
      - postgres_config:/etc/postgres
    networks:
      - database
  redis:
    image: redis:7.0-rc2-alpine3.15
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - tasks
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    hostname: herbarioRabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment:   
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - tasks
  frontend:
    container_name: herbarium_frontend
    build: ./Nuxt
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - herbario
  backend:
    container_name: herbarium_backend
    build: ./Flask
    ports:
      - 5001:5000
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_APP=manager:app
    depends_on:
      - db
    networks:
      - herbario
      - tasks
      - database
    command: flask run
  worker:
    container_name: celery
    build: ./Flask
    depends_on:
      - db
      - redis
      - rabbitmq
      - backend
    links:
      - db
      - redis
      - rabbitmq
    networks:
      - tasks
      - database
    environment:
      - broker_url='amqp://guest:guest@rabbitmq:5672//'
      - cache_backend='redis://redis:6379/0'
      - result_backend='redis://redis:6379/1'
    command: celery -A celery_worker.celery worker --loglevel=info 
    
      